In [2]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')

b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                    feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step % 100 == 0:
        print('step:', step, 'Cost:', cost_val, '\nPrediction:\n', hy_val)

C:\Users\ui88g\anaconda3\envs\tf113\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\ui88g\anaconda3\envs\tf113\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\ui88g\anaconda3\envs\tf113\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\ui88g\anaconda3\envs\tf113\lib\site-packages\tensorflow\python\f

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
step: 0 Cost: 9575.35 
Prediction:
 [238.78906 288.74503 283.80566 307.57312 221.73204]
step: 100 Cost: 0.30183536 
Prediction:
 [151.95883 184.39253 180.97955 195.60023 142.1383 ]
step: 200 Cost: 0.3004494 
Prediction:
 [151.95308 184.39636 180.9776  195.60028 142.14209]
step: 300 Cost: 0.29911914 
Prediction:
 [151.94743 184.40007 180.97568 195.60034 142.14575]
step: 400 Cost: 0.29784647 
Prediction:
 [151.94196 184.40366 180.9738  195.60042 142.14928]
step: 500 Cost: 0.29661298 
Prediction:
 [151.93658 184.40718 180.97197 195.60054 142.1527 ]
step: 600 Cost: 0.29542089 
Prediction:
 [151.93137 184.41064 180.97018 195.60068 142.156  ]
step: 700 Cost: 0.29427478 
Prediction:
 [151.92625 184.41399 180.96843 195.60085 142.1592 ]
step: 800 Cost: 0.29317006 
Prediction:
 [151.92125 184.41727 180.96672 195.60103 142.16231]
step: 900 Cost: 0.29209787 
Prediction:
 [151.916

for many variables, this code is too complex

#### Improving by using matrix

In [4]:
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1], name='weight'))
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# simplified cost/lost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()

# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict={X:x_data, Y:y_data})
    if step % 100 == 0:
        print('step:', step, 'Cost:', cost_val, '\nPrediction\n', hy_val)

step: 0 Cost: 126121.6 
Prediction
 [[-159.22546]
 [-197.2163 ]
 [-191.33363]
 [-208.02669]
 [-152.1618 ]]
step: 100 Cost: 12.159109 
Prediction
 [[155.73917]
 [181.59718]
 [181.78825]
 [198.3048 ]
 [136.83037]]
step: 200 Cost: 11.551899 
Prediction
 [[155.61072]
 [181.68556]
 [181.74934]
 [198.27315]
 [136.94933]]
step: 300 Cost: 10.976598 
Prediction
 [[155.48576]
 [181.77159]
 [181.7115 ]
 [198.2423 ]
 [137.06516]]
step: 400 Cost: 10.431516 
Prediction
 [[155.36418]
 [181.8553 ]
 [181.6747 ]
 [198.21219]
 [137.17793]]
step: 500 Cost: 9.915052 
Prediction
 [[155.24588]
 [181.93675]
 [181.6389 ]
 [198.18283]
 [137.28775]]
step: 600 Cost: 9.425737 
Prediction
 [[155.13078]
 [182.01599]
 [181.60406]
 [198.15417]
 [137.39467]]
step: 700 Cost: 8.9621105 
Prediction
 [[155.01881]
 [182.09311]
 [181.57019]
 [198.12622]
 [137.49878]]
step: 800 Cost: 8.522844 
Prediction
 [[154.90987]
 [182.16814]
 [181.53726]
 [198.09897]
 [137.60016]]
step: 900 Cost: 8.1065855 
Prediction
 [[154.80386]
 [18